buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
//        classpath 'com.android.tools:r8:8.7.18'
        classpath 'com.android.tools.build:gradle:8.13.0'
    }
}

allprojects {

    ext {
        appName = '少前地牢'
        appPackageName = 'com.ngfpixel.gfchemistrypixeldungeon'

        appVersionCode = 631
        appVersionName = '0.5.3'

        appJavaCompatibility = JavaVersion.VERSION_17 //1_8

        appAndroidCompileSDK = 34
        appAndroidMinSDK = 19
        appAndroidTargetSDK = 34

        gdxVersion = '1.10.0'
        gdxControllersVersion = '2.2.1'
    }
    version = appVersionName

    repositories {
        google()
        mavenCentral()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    }
}
